### ISSUE TITLE
Multiple docker issues..

### ISSUE THREAD

**Issue by JourneyOver** [jjjchens235/bing-rewards#290]
Following the [container installation](https://github.com/jjjchens235/bing-rewards#container-installation), and the [compose file](https://github.com/jjjchens235/bing-rewards/blob/master/compose.yaml), I get a symlink permission denied error whenever it's trying to symlink the logs directory.

I've got the permissions set correctly and the config portion works just fine (other than when I restart the container it complains about the file already existing). I've tried with removing `UMASK=022` from the env variables, I've tried changing the mapping in the compose from `/bing` to `/bing-rewards/BingRewards/logs` but that brings up a different issue of `ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/bing-rewards/BingRewards/requirements.txt'` for some reason.

if I create the folders myself, I just end up getting a different error about the file exists, but it doesn't do any symlinks and the log files do not end up getting updated in the /bing folder,

if I remove the mapping in the compose for logs completely, it symlinks just fine with no issues at all, but then if I go to add the mapping back it just starts up with the problems all over again..

this is currently my compose file:
```
---
version: "3.8"

services:

  bing-rewards:
    image: docker.io/killerherts/bing-rewards:latest
    container_name: bing-rewards
    hostname: bing-rewards
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/Docker/Apps/BingRewards/config:/config
      - /mnt/Docker/Apps/BingRewards/logs:/bing
    stdin_open: true
    tty: true

networks:
  bunni_network:
    external: true
```

I've tried with having `UMASK=022` in the env section, I've tried with changing the `- /mnt/Docker/Apps/BingRewards/logs:/bing` to `/bing-rewards/BingRewards/logs` and everything else I've explained above.
